# Generated by Django 5.0.1 on 2024-01-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_audio', '0003_audiofile_delete_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
